services:
  - type: web
    name: data-analysys-and-pridication
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.8
